Repository Socorro-Projetao/socorro, pull requests merged in 2024-10, with the labels that each got.

#118 validacao de visualizacao dos perfis
  app/(app)/home.js
Labels: feature

#123 ajustes no campo de localizacao no cadastro de profissional
  app/signUpCliente.js
  app/signUpProfissional.js
  context/authContext.js
Labels: bug, feature

#124 ajuste no update do profissional
  app/profileUpdate.js
  app/signUpProfissional.js
Labels: bug

#126 BUG - erros de visualizacao
  app/profileUpdate.js
Labels: bug, tests

#127 icone de voltar para os opcoes de pesquisa
  app/pesquisaLocalizacao.js
Labels: bug

#128 consertando o padding das opcoes de selecao
  app/pesquisaLocalizacao.js
Labels: bug

#129 Funcionalidade de busca profissional por localização
  app/detalhesProfissional.js
  app/pesquisaLocalizacao.js
Labels: bug, feature

#130 funcionalidade de pesquisa por profissional
  app/pesquisaProfissional.js
Labels: feature

#131 rota para tela anterior
  app/detalhesProfissional.js
Labels: bug

#132 pesquisa por especialidade
  app/pesquisaEspecialidade.js
Labels: feature

#134 Inserção de links para redes sociais
  app/detalhesProfissional.js
Labels: feature

#135 Conserto de BUGS nas funções de pesquisa
  app/detalhesProfissional.js
  app/pesquisaEspecialidade.js
  app/pesquisaProfissional.js
Labels: bug

#136 juntando os cards dos profissionais
  app/pesquisaLocalizacao.js
Labels: bug

#137 alinhando os cards na parte superior
  app/pesquisaLocalizacao.js
Labels: bug

#138 Alterando configurações de seguranã
  .gitignore
  babel.config.js
  firebaseConfig.js
  package-lock.json
  package.json
Labels: configuration

#139 Revert "Alterando configurações de segurança"
  .gitignore
  babel.config.js
  firebaseConfig.js
  package-lock.json
  package.json
Labels: bug

#141 Navigator Drawer
  app/(app)/_layout.js
  app/(app)/homeProfissional.js
  components/HomeHeader.js
Labels: feature

#143 Home profissional
  app/(app)/home.js
  app/(app)/homeProfissional.js
  app/(app)/opcoesPesquisa.js
  app/pesquisaEspecialidade.js
  app/pesquisaLocalizacao.js
  app/pesquisaProfissional.js
  package.json
Labels: feature

#144 Alterando o front da home de cliente
  app/(app)/home.js
  package-lock.json
Labels: feature

#145 Listagem para o admin ver todos os perfis
  app/anunciantes.js
  app/clientes.js
  app/detalhesAnunciantes.js
  app/detalhesClientes.js
  app/profissionais.js
Labels: feature

#147 Adicionando exibição de anuncios
  app/(app)/home.js
Labels: feature

#150 feat: cliente consegue visualizar detalhes dos profissionais na home
  app/(app)/home.js
Labels: feature

#151 Adicionado o upload de imagens de clientes no S3
  .gitignore
  app/signUpCliente.js
  package-lock.json
  package.json
Labels: feature

#152 Adicionado o upload de imagens de anunciante no S3
  app/signUpAnunciante.js
Labels: feature

#153 Adicionado o upload de imagens de profissional no S3
  app/signUpCliente.js
  app/signUpProfissional.js
Labels: feature

#154 mostrando o email do anunciante
  app/detalhesAnunciantes.js
  context/authContext.js
Labels: feature

#156 feat: salvando imagem bucket ao editar
  app/profileUpdate.js
Labels: feature

#157 link de email
  app/detalhesAnunciantes.js
Labels: feature

#158 Adicionado validação de data de nascimento
  app/profileUpdate.js
  app/signUpProfissional.js
Labels: feature

#165 fix: visualizar perfil do profissional
  app/(app)/home.js
Labels: bug

#166 Ajuste no CSS
  app/detalhesProfissional.js
  app/profileRead.js
  app/profileUpdate.js
  app/signIn.js
Labels: bug

#167 fix: corrigido o problema da data ao editar
  app/profileUpdate.js
Labels: bug

#168 Correção do erro VirtualizedLists
  app/pesquisaLocalizacao.js
  app/signUpProfissional.js
Labels: bug

#169 bloqueando o list opções para perfis diferente de cliente
  app/(app)/_layout.js
Labels: bug

#170 adicionando imagem na pagina principal perfil diferente do cliente
  app/(app)/home.js
Labels: bug

#171 fix: solicitando login ao usuario tentar excluir a conta com a sessao expirada
  app/profileDelete.js
Labels: bug

#173 Negrito nas especialidades -> Tela inicial cliente
  app/(app)/home.js
Labels: bug

#174 Lendo anuncios do Firebase
  app/(app)/home.js
Labels: feature

#175 ajustes para upload do banner - proporcao
  app/(app)/home.js
  app/profileUpdate.js
  app/signUpAnunciante.js
Labels: bug

#176 Vídeo pitch
  README.md
Labels: documentation
