Repository Socorro-Projetao/socorro, pull requests merged in 2024-09, with the labels that each got.

#41 visualizar atributos de cada perfil
  app/profileRead.js
  context/authContext.js
Labels: feature

#44 alteração dos campos de cada perfil
  app/profileUpdate.js
  app/selectOptions.js
  app/signUpProfissional.js
Labels: feature

#54 fix: registrar profissional
  context/authContext.js
Labels: bug, feature

#55 Remoção do campo Área de atuação
  app/profileRead.js
Labels: feature

#56 Adicionado edição de profissional
  app/profileUpdate.js
Labels: feature

#63 Adicionado a remoção de usuário e profissional
  app/profileDelete.js
Labels: feature

#64 Incluindo campos novos
  app/profileRead.js
  app/profileUpdate.js
  app/selectSexOptions.js
  app/signUpCliente.js
  app/signUpProfissional.js
  context/authContext.js
Labels: bug, feature

#66 ajuste do delete dos perfis
  app/profileDelete.js
Labels: bug, feature

#72 alteracao no nome do campo de rede social
  app/profileRead.js
  app/profileUpdate.js
  app/signUpProfissional.js
  context/authContext.js
Labels: bug

#84 fix: corrigindo data no visualizar
  app/profileRead.js
  context/authContext.js
Labels: bug

#85 Adicionado o campo de data de nascimento no update
  app/profileUpdate.js
Labels: feature

#88 ajuste no campo de rede social
  README.md
  app/signUpProfissional.js
Labels: bug

#89 resolvendo bug tela cliente e profissional
  app/profileRead.js
  app/profileUpdate.js
  app/signUpCliente.js
  app/signUpProfissional.js
Labels: bug

#90 bug tela do profissional data - correção
  app/profileRead.js
Labels: bug

#91 Ajustes nas telas de remoção e edição
  app/profileDelete.js
  app/profileUpdate.js
Labels: bug, feature

#93 Revert "Telas Home Cliente e Profissional "
  app/(app)/home.js
  app/(app)/homeCliente.js
Labels: bug

#102 Telas de anunciante e admin
  app/admin.js
  app/anunciantes.js
  app/clientes.js
  app/profileSelection.js
  app/profileUpdate.js
  app/profissionais.js
  app/signIn.js
  app/signUpAnunciante.js
  app/signUpCliente.js
  app/signUpProfissional.js
  context/authContext.js
  firebaseConfig.js
Labels: feature

#106 campo de localizacao de profissional - cad e edit
  app/pesquisaLocalizacao.js
  app/profileUpdate.js
  app/signUpProfissional.js
Labels: bug, feature
